########################### SERVICES
services:
  ########################### DAINF LABS CLIENT
  lab-ca:
    image: lab-ca
    container_name: lab-ca
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "8612:80"
    labels:
      # Traefik Config
      - "traefik.enable=true"
      - "traefik.http.routers.lab-ca.tls=true"
      - "traefik.http.routers.lab-ca.rule=Host(`lab-ca.app.pb.utfpr.edu.br`)"
      - "traefik.http.routers.lab-ca.tls.certresolver=letsencrypt"
      - "traefik.http.routers.lab-ca.entrypoints=websecure"

    restart: unless-stopped
    networks:
      - web

########################### NETWORKS
networks:
  web:
    external: true
